core/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Navigable URLS: 
    path('', views.home), # Home page: where you start your journey
    path('search/', views.SearchView.as_view(), name='search'),

    path('signup/',views.SignUp,name='signup'),
    path('signin/',views.SignIn,name='signin'),
    path('signout/',views.SignOut,name='signout'),
    path('guide/', views.howtoguide,name='guide'),
    
    path('product/<str:product_id>', views.ProductView.as_view(), name='product'),
    path('productcompare/<str:product_id>/<str:viewingproduct_id>', views.CompareProductView.as_view(), name='compareProduct'),
    path('watchlists/', views.WatchlistsView.as_view(), name = 'watchlists'),
    path('watchlist/<int:watchlist_id>', views.WatchlistView.as_view(), name = 'watchlist'),
    path('profile/', views.profile, name='profile'),
    path('editprofile/', views.editProfile, name='editprofile'),
    path('addProductToWatchlist/', views.SearchView_Watchlist.as_view(), name = 'addProduct'),

    # API/data URLs
    path('get-product-details/', views.get_product_details, name='get_product_details'),
    path('create-watchlist/', views.create_new_watchlist, name='create_watchlist'),
    path('delete-watchlist/', views.delete_watchlist, name='delete_watchlist'),
    path('watchlist/add/<int:watchlist_id>/<str:product_id>', views.add_product_to_watchlist, name='add_product_to_watchlist'),
    path('watchlist/remove/<int:watchlist_id>/<str:product_id>', views.remove_product_from_watchlist, name='remove_product_from_watchlist'),
    path('is-product-in-watchlist/<int:watchlist_id>/<str:product_id>', views.is_product_in_watchlist, name='is_product_in_watchlist'),
    path('historical-price/<str:product_id>', views.historical_price, name='historical_price'),
    path('store-historical-price/<str:product_id>', views.store_historical_price, name='store_historical_price')
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Product(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    name = models.CharField(max_length=100, default="")
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    retailer = models.CharField(max_length=100)
    retailer_code = models.CharField(max_length=150)
    description = models.TextField(default="")
    category = models.CharField(max_length=100, default="")
    image_url = models.CharField(max_length=200, default="")

    def __str__(self):
        return self.name

class HistoricalPrice(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        ordering = ['-date']
        
    def __str__(self):
        return self.product.name

class Watchlist(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, default="New Watchlist")
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    products = models.ManyToManyField(Product)

    def __str__(self):
        return self.title

class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='profile')
    # Add additional fields for the user profile
    bio = models.TextField(max_length=500, default='')
    location = models.TextField(max_length=500, default='')
    # avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    birthdate = models.DateField(null=True, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return self.user.username

core/forms.py
from .models import *
from django import forms

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'email': 'Email',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'input', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'class': 'input', 'placeholder': 'Email'}),
        }


class ProfileForm(forms.ModelForm):
    birthdate = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'input'}),
        label='Birthdate',
        help_text='Select your birthdate'
    )

    class Meta:
        model = Profile
        fields = ('bio', 'location', 'birthdate')
        labels = {
            'bio': 'Bio',
            'location': 'Location',
        }
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'textarea', 'placeholder': 'Bio'}),
            'location': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Location'}),
        }

core/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404,redirect
from django.http import JsonResponse
from django.views import View
from django.views.generic import ListView
from core.forms import ProfileForm, UserForm
from django.contrib import messages
from .models import *
from .serializers import *
from core import scrapers
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.db import transaction
from datetime import date

def home(request):
     
    if  request.user.is_authenticated:
            
            return render(request, 'index.html')
    else:
        return redirect(SignIn)
    
def howtoguide(request):
    return render(request, 'howto.html')
 
def SignUp(request):
    if request.method == "POST":
        name = request.POST.get('username' )
        email = request.POST.get('useremail')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        if password1 == password2:
            if User.objects.filter(username=name):
                messages.info(request,"User already exists")
                return redirect(SignUp)
            else:
                user = User.objects.create_user(username=name,password=password1,email=email)
                user.save()
                messages.success(request, f'Your account has been created. You can log in now!')
                return redirect(SignIn)
        else:
            messages.success(request, 'Password does not match!')
    return render (request,'signup.html')

def SignIn(request):
    if request.method == "POST":
        name = request.POST.get('username')
        password = request.POST.get('password')    
        user = auth.authenticate(username=name,password = password)
        if user is not None:
            auth.login(request,user)
            request.session['user'] = name
            return redirect(home)
        else:

            messages.error(request,"Invalid username or password.")
    return render(request=request, template_name="signin.html")

def SignOut(request):
    logout(request)
    print("goooddddd")
    messages.success(request, "Logged Out Successfully!!")

    return redirect(SignIn)

# Page Views
class SearchView(ListView):
    model = Product
    template_name = 'search.html'

    def get_queryset(self):
        if self.request.GET.get('q') == None:
            object_list = Product.objects.none()
        else:
            query = self.request.GET.get('q')
            object_list = Product.objects.filter(name__icontains=query)

        return object_list

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        return context

class SearchView_Watchlist(ListView):
    model = Product
    template_name = 'addProduct.html'

    def get_queryset(self):
        if self.request.GET.get('q') == None:
            object_list = Product.objects.none()
        else:
            query = self.request.GET.get('q')
            object_list = Product.objects.filter(name__icontains=query)

        return object_list

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        context['another_value'] = self.request.GET.get('another_value')
        return context

class ProductView(View):
    model = Product
    template_name = 'product.html'

    def get(self, request, product_id):
        print(product_id)
        product = Product.objects.get(id=product_id)
        return render(request, 'product.html', {'viewingProduct': product})
    
class WatchlistsView(View):
    model = Watchlist
    template_name = 'watchlists.html'

    def get(self, request):
        user = request.user
        
        if user.is_anonymous: watchlists = []
        else:
            user_instance = User.objects.get(username=user.username)
            print(type(user_instance))
            watchlists = Watchlist.objects.filter(owner=user_instance)

        return render(request, self.template_name, {'watchlists': watchlists})

class WatchlistView(View):
    model = Watchlist
    template_name = 'watchlist.html'
    
    def get(self, request, watchlist_id):
        watchlist = Watchlist.objects.get(id=watchlist_id)

        # DEBUG
        for product in watchlist.products.all():
            print(product.name)
        
        # Ensure user owns the watchlist they are trying to view
        if request.user != watchlist.owner:
            return redirect('watchlists')

        return render(request, self.template_name, {'watchlist': watchlist})
    
class WatchlistAddProductView(View):
    model = Watchlist
    template_name = 'addProduct.html'
    
    def get(self, request, watchlist_id):
        watchlist = Watchlist.objects.get(id=watchlist_id)

        if request.user != watchlist.owner:
            return redirect('watchlists')

        return render(request, self.template_name, {'watchlist': watchlist})
    
class SearchView(ListView):
    model = Product
    template_name = 'search.html'

    def get_queryset(self):
        if self.request.GET.get('q') == None:
            object_list = Product.objects.none()
        else:
            query = self.request.GET.get('q')
            object_list = Product.objects.filter(name__icontains=query)

        return object_list

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        return context

class ProductView(View):
    model = Product
    template_name = 'product.html'

    def get(self, request, product_id):
        print(product_id)
        product = Product.objects.get(id=product_id)
        watchlists = Watchlist.objects.filter(owner=request.user)
        stop_words = set(['the', 'and', 'a', 'an', 'in', 'on', 'at', 'is', 'it', 'of', 'for','with','Woolworths', 'Coles',
                      'Aldi' 'woolworths', 'coles',
                      'aldi','No','Yes','Each','each','Pack','Pack','bottle','Bottle'])  # Define your own set of stopwords
        description = product.name
        description = description.lower()

        # Remove punctuation
        punctuation = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'
        description = description.translate(str.maketrans('', '', punctuation))

        # Split into words
        words = description.split()

        # Remove stopwords and words containing digits
        keywords = [word for word in words if word not in stop_words and not any(char.isdigit() for char in word)]

        combined_list = []

        for keyword in keywords:
            similar_lists = Product.objects.filter(name__icontains=keyword)
            combined_list.extend(similar_lists)

        combined_list = list(set(combined_list))  # Remove duplicate items
        
        # Retrieve historical prices
        historical_prices = HistoricalPrice.objects.filter(product=product).order_by('-date')
        
        context = {
            'viewingProduct': product,
            'watchlists': watchlists,
            'similarlists': combined_list,
            'historicalPrices': historical_prices
        }
        
        return render(request, 'product.html', context)
        
class CompareProductView(View):
    model = Product
    template_name = 'compareProduct.html'
    def get(self, request, product_id,viewingproduct_id):
        
        product = Product.objects.get(id=product_id)
        product2 = Product.objects.get(id=viewingproduct_id)
        return render(request, 'compareProduct.html', {
            'viewingProduct': product2,
            'Product': product,
             
            })
# API  or Data Views

def get_product_details(request):
    # Get product id from AJAX request
    product_id = request.POST.get('product_id')

    # Get product *retailer* id from the database
    product = Product.objects.get(id=product_id)
        
    # Scrape for product details
    scraper = scrapers.ProductDetailsScraper()
    product_details = scraper.scrape(product.retailer_code, product.retailer)

    # Update product details in database
    product.description = product_details["description"]
    product.save()

    ajax_response = {
        "description": product_details["description"],
    }

    return JsonResponse(ajax_response, status=200)

@auth.decorators.login_required
def create_new_watchlist(request):
    if request.method == 'POST':
        # Get watchlist title from AJAX request
        watchlist_title = request.POST.get('watchlist_title')
        
        # Check if watchlist title is empty
        if watchlist_title is None: 
            return JsonResponse({"error": "Watchlist title is required"}, status=400)

        # Check if user is authenticated
        if not request.user.is_authenticated: 
            return JsonResponse({"error": "User is not authenticated"}, status=401)
            
        # Create new watchlist
        user_instance = request.user

        watchlist = Watchlist.objects.create(title=watchlist_title, owner=user_instance)
        ajax_response = {
            "message": "Watchlist created successfully",
            "watchlist_id": watchlist.id,
            "watchlist_title": watchlist.title,
        }

        return JsonResponse(ajax_response, status=200)

@auth.decorators.login_required
def delete_watchlist(request):
    if request.method == 'POST':

        # Get watchlist id from AJAX request
        watchlist_id = request.POST.get('watchlist_id')

        # Check if user is authenticated
        if not request.user.is_authenticated: 
            return JsonResponse({"error": "User is not authenticated"}, status=401)

        # Check if watchlist exists
        if not Watchlist.objects.filter(id=watchlist_id).exists(): 

core/templates/addProduct.html
{% extends 'bases/base_page.html' %}
{% load static %}

{% block content %}

<div class="block">
    {% comment %} <h1 class="title">Search</h1> {% endcomment %}
</div>

<div class="block">
    
    <div class="columns is-centered">
        <div class="column is-half">

            <div class="block">
                {% comment %} {% include 'components/product_searchbar.html' %} {% endcomment %}
                <h1 class="title">Showing results for "<span class="is-italic">{{ query }}</span>"</h1>
                <h1 class="title">Showing results for watchlist id = "<span class="is-italic">{{ another_value }}</span>"</h1>
            </div>

            <div class="block">

                {% comment %} search results {% endcomment %}
                {% if product_list %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Retailer</th>
                            <th>Image</th>
                            <th>Product Name</th>
                            <th>Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in product_list %}      
                        <tr>
                            <td>
                                <figure class="image is-32x32">
                                    <img src="{% static 'img/' %}{{ product.retailer }}.png" alt="">
                                </figure>
                            </td>
                            <td>
                                <figure class="image is-64x64">
                                    <img src="{{ product.image_url }}" alt="">
                                </figure>
                            </td>
                            <td><a href="{% url 'product' product.id %}">{{ product.name }}</a></td>
                            <td>${{ product.price }}</td>
                            <td><button class="add-to-watchlist-button button is-primary" data-product-id="{{ product.id }}">Add</button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                {% endif %}

            </div>
        </div>
    </div>
    
</div>

{% endblock content %}

{% block javascript %}
<script>

    $(document).ready(function() {
        $('.add-to-watchlist-button').click(function() {
            var selectedWatchlistId = '{{ another_value }}';
            let watchlist_ID_Int = parseInt(selectedWatchlistId);
            var product_id = $(this).data('product-id');

            $.ajax({
                url: "/watchlist/add/" + watchlist_ID_Int + "/" + product_id,
                method: "POST",
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    if (response.status === 'success') {
                        //alert("hello");
                    } else {
                        //alert(response.message);
                    }
                    window.location.href = '/watchlist/'+watchlist_ID_Int;
                },
                error: function(xhr, status, error) {
                    alert('An error occurred: ' + error);
                }
            });
        });
    });

</script>
{% endblock javascript %}

core/templates/compareProduct.html
{% extends 'bases/base_page.html' %}
{% load static %}

{% block content %}

<div class="columns is-centered">
    <div class="column">
        <div class="block">
    
            
            <div class="card">

                <!-- Product image -->
                <div class="card-image">
                    <figure class="image">
                        <img id="product-image" class="p-4" src="{{ viewingProduct.image_url }}" alt="Product image">
                    </figure>
                </div>

                <div class="card-content">

                    <div class="block">
                        <p class="title">{{ viewingProduct.name }}</p>

                        <!-- Price tag -->
                        <span class="tag has-addons is-white is-medium px-0">
                            <span class="tag is-white is-medium">
                                <figure class="image is-32x32">
                                    <img src="{% static 'img/' %}{{ viewingProduct.retailer }}.png" alt="{{ viewingProduct.retailer }}">
                                </figure>
                            </span>
                            <span class="tag is-medium has-background-primary-light"><strong>${{ viewingProduct.price }}</strong></span>
                        </span>
                    </div>

                    <!-- Product description box -->
                    <div id="product-description" class="box mb-0">
                        <p class="heading">Product Description</p>
                        <p id="product-description-content">{{ viewingProduct.description }}</p>
                    </div>

                    <!-- Loading indicator for when additional details are being gotten -->
                    <progress id="loading-indicator" class="progress is-small is-primary is-hidden mt-4" max="100">30%</progress>
                </div>
            </div>
        </div>
        
    </div>
    

    <!-- This is the right side where we have actions related to the products-->
    <div class="column">
        <div class="card">

            <!-- Product image -->
            <div class="card-image">
                <figure class="image">
                    <img id="product-image" class="p-4" src="{{ Product.image_url }}" alt="Product image">
                </figure>
            </div>

            <div class="card-content">

                <div class="block">
                    <p class="title">{{ Product.name }}</p>

                    <!-- Price tag -->
                    <span class="tag has-addons is-white is-medium px-0">
                        <span class="tag is-white is-medium">
                            <figure class="image is-32x32">
                                <img src="{% static 'img/' %}{{ Product.retailer }}.png" alt="{{ Product.retailer }}">
                            </figure>
                        </span>
                        <span class="tag is-medium has-background-primary-light"><strong>${{ Product.price }}</strong></span>
                    </span>
                </div>

                <!-- Product description box -->
                <div id="product-description" class="box mb-0">
                    <p class="heading">Product Description</p>
                    <p id="product-description-content">{{ Product.description }}</p>
                </div>

                <!-- Loading indicator for when additional details are being gotten -->
                <progress id="loading-indicator" class="progress is-small is-primary is-hidden mt-4" max="100">30%</progress>
            </div>
        </div>
       
    
    </div>
   
        
       

    
</div>

{% endblock %}

{% block javascript %}
{% comment %} for some reason moving this js to a static/ file it causes csrf_token errors {% endcomment %}
<script>
    $(document).ready(function() {
        
        updateActionButtons();
        
        // Get product details
        $.ajax({
            url: "/get-product-details/",
            type: "POST",
            data: {
                'product_id': '{{ product.id }}',
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            beforeSend: function() {
                // unhide the loading indicator
                $('#loading-indicator').removeClass('is-hidden');

                // if the product-description-content text is empty, hide the product description box
                if ($('#product-description-content').text() == "") {
                    $('#product-description').addClass('is-hidden');
                }
            },
            success: function(response) {
                $('#product-description-content').text(response.description);

                // unhide the product description box
                $('#product-description').removeClass('is-hidden');
            },
            error: function(xhr, status, error) {
                console.log(xhr.responseText);
            },
            complete: function() {
                // hide the loading indicator
                $('#loading-indicator').addClass('is-hidden');
            }
        });
        
        
        // Add product to watchlist button
        $('#add-to-watchlist-button').click(function() {
            var selectedWatchlistId = $('#watchlist-dropdown').val();
            var productId = '{{ product.id }}';
            
            // Send add request via ajax
            $.ajax({
                url: "/watchlist/add/" + selectedWatchlistId + "/" + productId,
                method: "POST",
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    updateActionButtons();
                },
                error: function(xhr, status, error) {
                    console.log(error);
                }
            });
        });
        
        // Remove product from watchlist
        $('#remove-from-watchlist-button').click(function(e) {
            e.preventDefault();
            var watchlist_id = $('#watchlist-dropdown').val();
            var product_id = '{{ product.id }}';
            
            // Send remove request via ajax
            $.ajax({
                url: "/watchlist/remove/" + watchlist_id + "/" + product_id,
                type: 'POST',
                data: {
                    'watchlist_id': watchlist_id,
                    'product_id': product_id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    updateActionButtons();
                },
                error: function(xhr, status, error) {
                    console.log(error);
                }
            });
        });
    });
    
    function updateActionButtons () {
        // Get the currently selected watchlist from the dropdown
        var selectedWatchlistId = $('#watchlist-dropdown').val();
        var productId = '{{ product.id }}';
        
        // If the product is already in the watchlist, disable the add button
        $.ajax({
            url: "/is-product-in-watchlist/" + selectedWatchlistId + "/" + productId,
            type: "POST",
            data: {
                watchlist_id: selectedWatchlistId,
                product_id: productId,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response) {
                if (response.status == true) {
                    // Product is already in the watchlist
                    $('#add-to-watchlist-button').addClass('is-hidden');
                    $('#remove-from-watchlist-button').removeClass('is-hidden');
                    return;
                } else if (response.status == false) {
                    // Product is not in the watchlist
                    $('#add-to-watchlist-button').removeClass('is-hidden');
                    $('#remove-from-watchlist-button').addClass('is-hidden');
                } else {
                    console.log("error");
                }
            },
        })
    }
    
</script>

{% endblock javascript %}

core/templates/editprofile.html
{% extends 'bases/base_page.html' %}

{% block content %}

<section class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <div class="columns">
                <div class="column">
                    <h1 class="title">
                        Welcome, {{ user.first_name }}!
                    </h1>
                    <h2 class="subtitle">
                        Edit Profile
                    </h2>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <div class="column is-half">
                <div class="box">
                    <h1 class="title">Edit Profile</h1>
                    <form method="post">
                        {% csrf_token %}
                        <div class="columns">
                            <div class="column">
                                {{ user_form.first_name.label_tag }}
                                {{ user_form.first_name }}
                            </div>
                            <div class="column">
                                {{ user_form.last_name.label_tag }}
                                {{ user_form.last_name }}
                            </div>
                        </div>

                        <div class="columns">
                            <div class="column">
                                {{ user_form.email.label_tag }}
                                {{ user_form.email }}
                            </div>
                        </div>

                        <div class="columns">
                            <div class="column">
                                {{ profile_form.bio.label_tag }}
                                {{ profile_form.bio }}
                            </div>
                            <div class="column">
                                {{ profile_form.location.label_tag }}
                                {{ profile_form.location }}
                            </div>
                        </div>

                        <div class="columns">
                            <div class="column">
                                {{ profile_form.birthdate.label_tag }}
                                {{ profile_form.birthdate }}
                            </div>
                        </div>

                        <button class="button is-link is-primary" type="submit">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

core/templates/search.html
{% extends 'bases/base_page.html' %}
{% load static %}

{% block content %}

<div class="block">
    
    <div class="columns is-centered">
        <div class="column is-half">

            <div class="block">
                <h1 class="title">Showing results for "<span class="is-italic">{{ query }}</span>"</h1>
            </div>

            <div class="block">

                {% if product_list %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Retailer</th>
                            <th>Image</th>
                            <th>Product Name</th>
                            <th>Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in product_list %}      
                        <tr>
                            <td>
                                <figure class="image is-32x32">
                                    <img src="{% static 'img/' %}{{ product.retailer }}.png" alt="">
                                </figure>
                            </td>
                            <td>
                                <figure class="image is-64x64">
                                    <img src="{{ product.image_url }}" alt="">
                                </figure>
                            </td>
                            <td><a href="{% url 'product' product.id %}">{{ product.name }}</a></td>
                            <td>${{ product.price }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                {% endif %}

            </div>
        </div>
    </div>
    
</div>

{% endblock content %}

{% block javascript %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("searchbar").value = "{{ query }}";
        document.getElementById("searchbar").focus();
    });
</script>
{% endblock javascript %}